development:
  sessions:
    default:
      database: stockroom
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: stockroom
      hosts:
        - localhost:27017